// src/config/worlds.config.js
// 10 Archaeological Restoration Guild Worlds for ScrollQuest (Grade 7 Math)

export const WORLDS = [
  {
    id: 0,
    name: "The First Fragment",
    emoji: "🏺",
    accent: "var(--world-0)",
    description: "Find one missing middle term, choosing an efficient method",
    conceptFocus: "find-single-middle-gap",
    boss: { name: "The Crumbling Fragment", emoji: "🏺", reward: "Restorer's Badge" },
  },
  {
    id: 1,
    name: "The Weathered Beginning",
    emoji: "📜",
    accent: "var(--world-1)",
    description: "Find a missing early/first term by reasoning backward",
    conceptFocus: "find-missing-early-term",
    boss: { name: "The Faded Opening", emoji: "📜", reward: "Origin Badge" },
  },
  {
    id: 2,
    name: "The Broken Ending",
    emoji: "🗿",
    accent: "var(--world-2)",
    description: "Find a missing last/far term efficiently",
    conceptFocus: "find-missing-far-term",
    boss: { name: "The Lost Ending", emoji: "🗿", reward: "Closure Badge" },
  },
  {
    id: 3,
    name: "Twin Gaps",
    emoji: "🕳️",
    accent: "var(--world-3)",
    description: "Find two or more missing terms, staying consistent",
    conceptFocus: "find-multiple-missing-terms",
    boss: { name: "The Double Gap Guardian", emoji: "🕳️", reward: "Twin Badge" },
  },
  {
    id: 4,
    name: "The Restoration Ledger",
    emoji: "📊",
    accent: "var(--world-4)",
    description: "Find missing terms in a table, incl. non-consecutive positions",
    conceptFocus: "missing-terms-tabular-format",
    boss: { name: "The Ledger Keeper", emoji: "📊", reward: "Archivist Badge" },
  },
  {
    id: 5,
    name: "The Merchant's Missing Coin",
    emoji: "👻",
    accent: "var(--world-5)",
    description: "Find a missing term embedded in a word problem",
    conceptFocus: "missing-terms-word-problem",
    boss: { name: "The Merchant's Ghost", emoji: "👻", reward: "Trader's Badge" },
  },
  {
    id: 6,
    name: "Choose Your Tool",
    emoji: "🤔",
    accent: "var(--world-6)",
    description: "Explicitly practice choosing term-to-term vs. general term",
    conceptFocus: "select-efficient-method",
    boss: { name: "The Indecisive Excavator", emoji: "🤔", reward: "Strategist Badge" },
  },
  {
    id: 7,
    name: "Deriving the Master Key",
    emoji: "🗝️",
    accent: "var(--world-7)",
    description: "Derive the general term when it's the efficient path",
    conceptFocus: "derive-general-term-when-efficient",
    boss: { name: "The Master Key Guardian", emoji: "🗝️", reward: "Key Badge" },
  },
  {
    id: 8,
    name: "Double-Checking the Restoration",
    emoji: "🧐",
    accent: "var(--world-8)",
    description: "Verify a filled gap two independent ways",
    conceptFocus: "cross-verify-missing-term",
    boss: { name: "The Skeptical Curator", emoji: "🧐", reward: "Verifier Badge" },
  },
  {
    id: 9,
    name: "The Grand Archive Unveiling",
    emoji: "🏛️",
    accent: "var(--world-9)",
    description: "Mixed review of every concept above; hardest boss",
    conceptFocus: "mixed-review",
    boss: { name: "The Grand Archivist", emoji: "🏛️", reward: "Master Restorer Trophy" },
  },
];

export const PLAY_MODES = [
  {
    id: 'guided',
    name: 'Guided Practice',
    icon: '🧭',
    desc: '5 questions with hints, no time pressure',
  },
  {
    id: 'independent',
    name: 'Independent Mode',
    icon: '🎯',
    desc: '10 questions, no hints, test true mastery',
  },
  {
    id: 'timed',
    name: 'Timed Challenge',
    icon: '⚡',
    desc: '8 questions in 60 seconds speed run',
  },
  {
    id: 'boss',
    name: 'Boss Battle',
    icon: '👑',
    desc: '5 boss-tier questions, 3 lives!',
  },
];
